project_id = "gsnsjrfudxyczpldbkzc"

[functions.send-email-verification]
verify_jwt = false

[functions.create-zoom-meeting]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
